
-- Seed data para preguntas RIASEC: 10 preguntas por cada letra (R, I, A, S, E, C)
-- Las preguntas son objetivas y diseñadas para medir preferencias claras.
INSERT INTO preguntas (texto, categoria) VALUES
	-- R: Realista
	('Prefiero trabajar con herramientas y maquinaria en lugar de pasar horas en una oficina', 'R'),
	('Me siento cómodo reparando, construyendo o ajustando objetos físicos', 'R'),
	('Disfruto actividades que requieren coordinación manual y precisión', 'R'),
	('Prefiero tareas donde el resultado práctico sea evidente al final del día', 'R'),
	('Me interesa aprender sobre electricidad, mecánica o mantenimiento', 'R'),
	('Me atrae trabajar al aire libre en proyectos concretos y visibles', 'R'),
	('Prefiero seguir instrucciones técnicas claras para ejecutar una tarea', 'R'),
	('Me siento competente usando herramientas manuales o eléctricas', 'R'),
	('Disfruto resolver problemas físicos mediante prueba y error práctico', 'R'),
	('Me motiva ver resultados tangibles de mi trabajo (objetos construidos o arreglados)', 'R'),

	-- I: Investigador
	('Disfruto analizar datos e investigar causas detrás de un problema', 'I'),
	('Prefiero tareas que requieren pensamiento crítico y experimentación', 'I'),
	('Me interesa comprender teorías y principios científicos', 'I'),
	('Disfruto leer artículos técnicos y aprender nuevos métodos de investigación', 'I'),
	('Me atrae diseñar experimentos o pruebas para validar hipótesis', 'I'),
	('Prefiero trabajar con conceptos abstractos antes que con actividades manuales', 'I'),
	('Me siento cómodo usando matemáticas o estadística para resolver problemas', 'I'),
	('Disfruto explorar nuevas ideas y modelar escenarios teóricos', 'I'),
	('Me motiva profundizar en un tema hasta entender sus detalles técnicos', 'I'),
	('Prefiero trabajos donde se investigue y se genere nuevo conocimiento', 'I'),

	-- A: Artístico
	('Disfruto crear o diseñar piezas que expresen una idea o estilo propio', 'A'),
	('Prefiero actividades abiertas a la interpretación más que tareas muy estructuradas', 'A'),
	('Me interesa experimentar con colores, formas, sonidos o palabras', 'A'),
	('Disfruto producir trabajos originales en vez de repetir instrucciones fijas', 'A'),
	('Me atrae trabajar en proyectos donde la estética importa mucho', 'A'),
	('Prefiero campos que permitan la expresión personal y la innovación', 'A'),
	('Me siento motivado al recibir libertad creativa para resolver un encargo', 'A'),
	('Disfruto combinar distintas disciplinas (arte, música, escritura, diseño)', 'A'),
	('Me interesa comunicar emociones o ideas a través de creaciones visuales o sonoras', 'A'),
	('Prefiero ambientes flexibles donde pueda experimentar con nuevas formas', 'A'),

	-- S: Social
	('Me siento cómodo ayudando y enseñando a otras personas directamente', 'S'),
	('Disfruto trabajar en equipo y colaborar para alcanzar objetivos comunes', 'S'),
	('Prefiero tareas donde pueda brindar apoyo emocional o práctico a otros', 'S'),
	('Me interesa la resolución de conflictos y la mediación entre personas', 'S'),
	('Disfruto planificar actividades que mejoren el bienestar de un grupo', 'S'),
	('Prefiero trabajos que impliquen contacto humano frecuente y directo', 'S'),
	('Me motiva ver el progreso de otras personas gracias a mi ayuda', 'S'),
	('Disfruto escuchar y aconsejar a quienes lo necesitan', 'S'),
	('Me siento capaz de explicar conceptos complejos de forma sencilla a otros', 'S'),
	('Prefiero ambientes laborales orientados al servicio y la cooperación', 'S'),

	-- E: Emprendedor
	('Me gusta tomar decisiones y liderar proyectos con responsabilidad', 'E'),
	('Prefiero trabajar en metas que impliquen negociar y persuadir a otros', 'E'),
	('Me atrae asumir riesgos calculados para conseguir objetivos comerciales', 'E'),
	('Disfruto planear estrategias para influir en el comportamiento de grupos', 'E'),
	('Me motiva organizar recursos para generar resultados económicos', 'E'),
	('Prefiero entornos competitivos donde pueda medir el impacto de mis acciones', 'E'),
	('Me siento capaz de vender ideas, productos o servicios eficazmente', 'E'),
	('Disfruto crear y gestionar equipos para cumplir objetivos concretos', 'E'),
	('Me interesa supervisar y optimizar procesos orientados a resultados', 'E'),
	('Prefiero roles con autoridad para tomar decisiones operativas o comerciales', 'E'),

	-- C: Convencional
	('Prefiero trabajar con datos organizados y procedimientos establecidos', 'C'),
	('Me siento cómodo manteniendo registros precisos y siguiendo reglas', 'C'),
	('Disfruto tareas repetitivas que requieren atención al detalle', 'C'),
	('Prefiero ambientes laborales estructurados con roles y tareas claras', 'C'),
	('Me interesa optimizar procesos administrativos y de control', 'C'),
	('Me motiva trabajar con sistemas contables, archivos o bases de datos', 'C'),
	('Disfruto realizar labores que requieren orden y cumplimiento de normas', 'C'),
	('Prefiero usar listas, formularios y procedimientos para completar tareas', 'C'),
	('Me siento competente en tareas que requieren precisión y diligencia', 'C'),
	('Prefiero roles administrativos donde la exactitud sea importante', 'C');


-- Seed data para 100 carreras con porcentajes por letra R/I/A/S/E/C y una breve descripción.
-- Los porcentajes representan un perfil ideal, no contienen carreras repetidas, ni especializaciones poco conocidas.
INSERT INTO carreras (nombre, porcentaje_R, porcentaje_I, porcentaje_A, porcentaje_S, porcentaje_E, porcentaje_C, descripcion) VALUES
	('Ingeniería Mecánica', 30,10,5,5,10,40,'Diseño, construcción y mantenimiento de máquinas y sistemas mecánicos.'),
	('Ingeniería Eléctrica', 25,20,5,5,10,35,'Sistemas eléctricos, generación y distribución de energía.'),
	('Ingeniería Civil', 35,10,5,5,10,35,'Planificación, diseño y construcción de infraestructuras y obras públicas.'),
	('Tecnología Mecatrónica', 30,20,10,5,10,25,'Integración de mecánica, electrónica y control para sistemas automatizados.'),
	('Técnico en Mantenimiento Industrial', 40,5,5,5,5,40,'Operación y reparación de equipos industriales y maquinaria.'),
	('Física', 10,45,5,5,5,30,'Estudio de las leyes fundamentales de la naturaleza y sus aplicaciones.'),
	('Química', 10,40,5,5,5,35,'Investigación y aplicación de procesos químicos en industria y laboratorio.'),
	('Biología', 5,45,5,5,5,35,'Ciencia de los seres vivos y sus procesos biológicos.'),
	('Matemáticas', 5,50,5,5,5,30,'Teoría matemática y resolución de problemas cuantitativos complejos.'),
	('Ciencias de la Computación', 10,50,10,5,10,15,'Desarrollo de software, algoritmos y sistemas informáticos.'),
	('Ingeniería de Software', 10,40,15,5,15,15,'Diseño, desarrollo y mantenimiento de aplicaciones y sistemas.'),
	('Inteligencia Artificial', 5,55,10,5,10,15,'Investigación y desarrollo de sistemas inteligentes y aprendizaje automático.'),
	('Análisis de Datos', 5,50,10,5,10,20,'Extracción de valor de datos mediante estadísticas y modelos predictivos.'),
	('Arquitectura', 10,10,40,5,10,25,'Diseño de espacios y edificaciones con criterio estético y funcional.'),
	('Diseño Gráfico', 5,5,60,5,5,20,'Creación de piezas visuales para comunicación, publicidad y medios.'),
	('Diseño de Interiores', 10,5,50,5,5,25,'Diseño funcional y estético de espacios interiores residenciales y comerciales.'),
	('Artes Plásticas', 5,5,70,5,5,10,'Expresión artística mediante pintura, escultura y otras técnicas plásticas.'),
	('Música', 5,5,65,5,5,15,'Composición, interpretación y producción musical.'),
	('Teatro', 5,5,65,10,5,10,'Interpretación dramática y producción teatral.'),
	('Psicología', 5,20,15,35,10,15,'Estudio del comportamiento humano y apoyo en salud mental y educación.'),
	('Trabajo Social', 5,10,10,50,10,15,'Intervención social para mejorar la calidad de vida de individuos y comunidades.'),
	('Enfermería', 10,10,10,50,5,15,'Cuidado directo de pacientes y apoyo en entornos de salud.'),
	('Educación Primaria', 5,10,10,55,10,10,'Formación y enseñanza de niños en etapas escolares iniciales.'),
	('Educación Física', 20,5,20,45,5,5,'Promoción de la actividad física y habilidades deportivas en contextos educativos.'),
	('Medicina', 10,30,5,25,5,25,'Diagnóstico, tratamiento y prevención de enfermedades en personas.'),
	('Odontología', 25,15,5,20,5,30,'Atención, tratamiento y prevención de enfermedades bucales.'),
	('Farmacia', 10,35,5,10,5,35,'Desarrollo, control y dispensación de medicamentos.'),
	('Nutrición', 10,20,10,35,5,20,'Asesoría y planificación dietética para la salud y el rendimiento.'),
	('Administración de Empresas', 10,15,10,10,35,20,'Gestión empresarial, finanzas y operaciones organizacionales.'),
	('Economía', 5,40,5,10,30,10,'Estudio de la producción, distribución y consumo de bienes y servicios.'),
	('Comercio Internacional', 5,20,10,10,40,15,'Operaciones comerciales a escala global y logística internacional.'),
	('Marketing', 5,20,15,10,40,10,'Estrategias de mercado, comunicación y posicionamiento de productos.'),
	('Ventas Profesionales', 5,10,10,10,55,10,'Actividades de venta y negociación comercial directa con clientes.'),
	('Finanzas', 5,30,5,10,45,5,'Gestión de inversiones, análisis financiero y mercados de capital.'),
	('Contaduría', 5,10,5,5,20,55,'Registro y control de operaciones contables y cumplimiento fiscal.'),
	('Recursos Humanos', 5,15,10,35,20,15,'Gestión de personal, selección y desarrollo organizacional.'),
	('Derecho', 5,25,10,15,30,15,'Estudio y aplicación de normas jurídicas y representación legal.'),
	('Ciencias Políticas', 5,35,10,30,10,10,'Análisis de sistemas políticos, políticas públicas y gobierno.'),
	('Relaciones Internacionales', 5,30,10,30,15,10,'Estudio de la diplomacia, políticas exteriores y cooperación global.'),
	('Comunicación Social', 5,15,20,30,15,15,'Medios de comunicación, periodismo y estrategias de información.'),
	('Periodismo', 5,15,20,30,15,15,'Cobertura informativa, investigación y producción de contenidos periodísticos.'),
	('Publicidad', 5,10,30,15,30,10,'Creación de campañas persuasivas para promover productos o ideas.'),
	('Diseño Web', 5,25,30,5,15,20,'Desarrollo y diseño de interfaces y experiencias en sitios web.'),
	('Desarrollo Front-end', 5,30,25,5,10,25,'Construcción de interfaces web interactivas y usables.'),
	('Desarrollo Back-end', 10,45,10,5,10,20,'Programación de servidores, bases de datos y lógica de negocio.'),
	('Administración Pública', 5,25,10,40,15,5,'Gestión de políticas públicas y administración gubernamental.'),
	('Gestión de Proyectos', 10,20,10,20,30,10,'Planificación, ejecución y seguimiento de proyectos multidisciplinares.'),
	('Logística y Cadena de Suministro', 20,10,5,10,40,15,'Planeación y control de flujos de bienes y operaciones logísticas.'),
	('Ingeniería Ambiental', 25,25,5,10,10,25,'Soluciones técnicas para protección ambiental y manejo de recursos.'),
	('Ciencias Ambientales', 10,40,5,10,10,25,'Estudio interdisciplinario del medio ambiente y conservación.'),
	('Agronomía', 35,20,5,5,5,30,'Producción agrícola, manejo de cultivos y sistemas agropecuarios.'),
	('Veterinaria', 30,20,5,25,5,15,'Atención de la salud animal y manejo de ganadería y mascotas.'),
	('Arquitectura del Paisaje', 20,15,40,10,5,10,'Diseño de espacios exteriores y planificación paisajística.'),
	('Urbanismo', 20,20,15,20,10,15,'Planificación y gestión del crecimiento y uso del suelo urbano.'),
	('Ingeniería Industrial', 30,25,5,10,15,15,'Optimización de procesos productivos y sistemas industriales.'),
	('Seguridad e Higiene Industrial', 35,10,5,10,10,30,'Prevención de riesgos laborales y control de higiene en industrias.'),
	('Criminología', 10,30,5,20,10,25,'Estudio de la delincuencia, prevención y sistemas de justicia penal.'),
	('Forense', 10,40,5,15,5,25,'Aplicación de técnicas científicas para investigar delitos y pruebas.'),
	('Ciberseguridad', 10,45,10,5,10,20,'Protección de sistemas informáticos y datos frente a ataques.'),
	('Sistemas de Información', 15,40,10,5,10,20,'Diseño y gestión de sistemas informática en organizaciones.'),
	('Telecomunicaciones', 20,30,10,5,10,25,'Diseño y gestión de redes de comunicación y transmisión de datos.'),
	('Gastronomía', 30,10,25,10,5,20,'Preparación profesional de alimentos, técnicas culinarias y gestión de cocina.'),
	('Hotelería y Turismo', 10,10,20,40,10,10,'Gestión de servicios de hospedaje, turismo y atención al cliente.'),
	('Bellas Artes', 5,5,75,5,5,5,'Estudios artísticos enfocados en producción y teoría del arte.'),
	('Optometría', 25,20,5,25,5,20,'Evaluación de la visión y cuidado de la salud visual.'),
	('Fonoaudiología', 10,25,10,40,5,10,'Prevención y tratamiento de alteraciones del habla y la comunicación.'),
	('Terapia Ocupacional', 15,20,10,40,5,10,'Rehabilitación para recuperar habilidades en actividades diarias.'),
	('Fisioterapia', 25,20,5,40,5,5,'Rehabilitación física para recuperar movilidad y reducir dolor.'),
	('Ingeniería Química', 20,35,5,5,5,30,'Procesos industriales y transformación de materias primas.'),
	('Biotecnología', 5,50,5,10,5,25,'Aplicación de procesos biológicos para producir bienes y servicios.'),
	('Genética', 5,60,5,5,5,20,'Estudio de la herencia y manipulación genética en organismos.'),
	('Anatomía Patológica', 10,45,5,10,5,25,'Estudio y diagnóstico de enfermedades mediante análisis de tejidos.'),
	('Radiología', 20,30,5,25,5,15,'Técnicas de imagen para diagnóstico médico y manejo de equipos.'),
	('Ingeniería de Alimentos', 25,30,5,5,5,30,'Desarrollo, producción y control de alimentos para consumo humano.'),
	('Sociología', 5,40,10,35,5,5,'Estudio de la sociedad, grupos humanos y procesos sociales.'),
	('Antropología', 5,50,10,25,5,5,'Estudio de las culturas humanas, su origen y diversidad.'),
	('Historia', 5,45,20,20,5,5,'Investigación y análisis de hechos y procesos históricos.'),
	('Letras / Filología', 5,35,30,20,5,5,'Estudio de lenguas, literatura y análisis textual.'),
	('Traducción e Interpretación', 5,30,20,30,5,10,'Conversión de textos y comunicación oral entre idiomas.'),
	('Bibliotecología', 5,20,10,50,5,10,'Gestión de bibliotecas, archivos y servicios de información.'),
	('Investigación de Mercado', 5,45,15,15,15,5,'Estudio de consumidores y comportamiento para estrategias comerciales.'),
	('Relaciones Públicas', 5,20,20,35,20,0,'Gestión de imagen y comunicación entre organizaciones y públicos.'),
	('Producción Audiovisual', 5,10,60,10,10,5,'Realización técnica y creativa de contenidos para cine y TV.'),
	('Producción Musical', 5,10,60,10,5,10,'Creación y producción de obras musicales y sonidos para medios.'),
	('Gestión Cultural', 5,10,45,30,5,5,'Organización de proyectos, eventos y políticas culturales.'),
	('Publicidad Digital', 5,20,30,10,35,0,'Gestión de campañas digitales y métricas de rendimiento en línea.'),
	('Analista de Políticas Públicas', 5,45,10,30,5,5,'Evaluación y diseño de políticas públicas basadas en evidencia.'),
	('Educación Especial', 5,15,10,50,10,10,'Intervención educativa para estudiantes con necesidades especiales.'),
	('Ingeniería de Petróleos', 30,25,5,5,5,30,'Exploración, extracción y explotación de recursos petrolíferos.'),
	('Oceanografía', 10,50,5,15,5,15,'Estudio científico de los océanos y sus procesos físicos y biológicos.'),
	('Meteorología', 10,50,5,15,5,15,'Estudio de la atmósfera y predicción del tiempo y clima.'),
	('Ciencias Actuariales', 5,60,5,5,20,5,'Evaluación cuantitativa de riesgos financieros e incertidumbre.'),
	('Seguros y Riesgos', 5,35,5,10,40,5,'Gestión y evaluación de riesgos para empresas y contratos de seguro.'),
	('Ingeniería Biomédica', 20,40,10,10,5,15,'Aplicación de ingeniería al diseño de dispositivos y soluciones médicas.'),
	('Ingeniería Industrial en Logística', 25,25,5,10,25,10,'Optimización de cadenas logísticas y sistemas de distribución.'),
	('Arte Dramático', 5,5,70,10,5,5,'Formación en actuación, interpretación y producción escénica.'),
	('Bachillerato en Humanidades', 5,30,35,25,5,0,'Formación amplia en áreas humanísticas y comunicación.'),
	('Técnico en Redes', 15,45,5,5,10,20,'Instalación y mantenimiento de infraestructuras de red y comunicaciones.'),
	('Gestión Ambiental', 15,35,10,20,5,15,'Políticas y prácticas para la sostenibilidad y manejo ambiental.'),
	('Ingeniería en Energías Renovables', 20,40,5,10,10,15,'Diseño e implementación de sistemas de energía sostenible.'),
	('Enología', 25,10,15,10,5,35,'Ciencia y técnica de la producción y elaboración del vino.'),
	('Diseño Industrial', 25,15,40,5,5,10,'Creación de productos funcionales y estéticamente trabajados.'),
	('Técnico en Sonido', 10,5,60,10,5,10,'Operación y producción técnica de audio en estudios y eventos.'),
	('Gestión Deportiva', 20,10,30,35,5,0,'Administración de organizaciones y eventos deportivos.'),
	('Terapia Respiratoria', 25,25,5,40,5,0,'Cuidado y tratamiento de pacientes con problemas respiratorios.'),
	('Educación Secundaria', 5,20,10,50,10,5,'Docencia especializada en adolescentes y contenido curricular.'),
	('Gestión Turística', 10,10,20,40,10,10,'Planificación y promoción de destinos y servicios turísticos.'),
	('Diseño de Producto', 20,10,50,5,5,10,'Diseño conceptual y técnico de bienes de consumo.'),
	('Ingeniería en Telecomunicaciones', 20,35,10,5,10,20,'Diseño y gestión de sistemas de comunicación y transmisión.'),
	('Investigación Clínica', 10,45,5,20,5,15,'Diseño y ejecución de estudios clínicos para evaluar tratamientos.');
